_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 7
                - 13
                - 19
                - 23
                - 38
                - 55
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 128
dropout:
    value: 0.35
epochs:
    value: 20
filter:
    value: 64
kernel_size:
    value: 3
kernel_size2:
    value: 9
learning_rate:
    value: 0.01
