_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 19
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
epochs:
    value: 1
input_scaling:
    value: 0.5
regularization:
    value: 1e-06
reservoir_size:
    value: 500
spectral_radius:
    value: 0.9
