_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 3
                - 8
                - 13
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "10":
                - 9
                - 17
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 32
d_model:
    value: 128
dropout:
    value: 0.1
epochs:
    value: 5
ff_dim:
    value: 256
learning_rate:
    value: 0.001
n_heads:
    value: 8
n_layers:
    value: 4
seq_length:
    value: 50
